---
title: Homework 1
author:
  - Xie zejian
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%H:%M, %d %B, %Y')`"
output:
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    latex_engine: xelatex
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,
                            message=FALSE,
                            echo=TRUE, 
                            fig.width=8)
## collapse = TRUE
# dec = 'jpeg'
# eval = FALSE
# https://yihui.org/knitr/options/#chunk-options

```

# Simple Example

Suppose one buy a call option $C$ which payoff $V_1=(S_1-K)^{+}$ at time $1$, $S_1$
can be $uS_0>K$ or $dS_0<K$ determined in probability space $(\left\{ H,T \right\},2^{\left\{ H,T \right\}},\mathop{{}\mathbb{P}})$.
To replicate such option, we construct our portfolio by buying
$\Delta_0$ stock and investing remaining in risk-free asset at return $r$:
$$
(V_0-\Delta_0S_0)(1+r)+\Delta_0S_1=(S_1-K)^{+}
$$
solve:
$$
V_0=\frac{p V_1(H)+qV_1(T)}{1+r},\Delta_0= \frac{V_1(H)-V_1(T)}{S_1(H)-S_1(T)}
$$
where $p=\frac{1+r-d}{u-d},q=1-p$.

$p$ and $q$ can be then seen as probability assigned to $\mathop{{}\mathbb{P}}\left\{ H \right\}$ and $\mathop{{}\mathbb{P}}\left\{ T \right\}$. Then $V_0$ is just the discounted of expected value of such option, such measure $\mathop{{}\mathbb{P}}$ is called **risk-neutral**.


# Single-period Model

Suppose $\bm{S_0}\in \mathbb{R}^{N}$ is price of $N$ stocks at time $0$, 
and $\bm{D}\in \mathbb{R}^{N\times n}$ is their price at time $t$ for $n$ states. 
For any portfolio $\bm{\theta}\in \mathbb{R}^{N}$, it cost $\bm{S_0'\theta}$ and 
its value is $\bm{D'\theta}\in \mathbb{R}^{n}$ for all $n$ states. 

An arbitrage is then defined as a portfolio $\theta, s.t.$ $\bm{S'\theta}$ have different sign with $\bm{D'\theta}$.


::: {.definition  name="State price"}

A state price vector is $\psi \in \mathbb{R}_{++}^{n}$ $s.t.$ $\bm{S_0}=\bm{D\psi}$.

:::

To justify the name of state price, suppose we want to "bet" the state of market, $i.e.$, we would like earning $\bm{1}_{state=i}$, then our portfolio supposed to be $\bm{D'\theta}=\bm{e_i}$, and it cost
$$
\bm{S_0'\theta}=\bm{\psi'D'\theta=\psi'e_i=}\psi _{i}
$$
so the coordinate of $\bm{\psi}$ is the price of "betting" a state.



::: {.theorem  name=""}

There is no arbitrage iff there is a state price vector.

:::


:::: {.proof}


::: {.theorem #SPH name="Separating Hyperplane Theorem"}

Suppose $M$ and $K$ are closed convex cones in $\mathbb{R}^{d}$ that $M \cap K=\left\{ \bm{0} \right\}$, if $K$ isn't a liner space, then there is a nonzero linear $f$ separated them, $i.e.$, $f(x)<f(y)$ for any $x\in M$ and $y \in K- \left\{ \bm{0} \right\}$.

:::


::: {.theorem #riesz name="Riesz Representation Theorem"}

Any continuous linear function $f$ on Hilbert space $\mathcal{H}$ can be written as $f(x)=\left\langle x,v \right\rangle$ for some $v \in \mathcal{H}$.

:::

Let $M=\left\{ (-\bm{S_0'\theta},\bm{D'\theta}):\theta \in \mathbb{R}^{N} \right\}$ and $K=\mathbb{R}_{+}\times \mathbb{R}_{+}^{n}$. Then there is no arbitrage iff $K\cap M=\left\{ \bm{0} \right\}$.

$\implies$, let $f$ be the functional in theorem \@ref(thm:SPH), note $M$ is a linear space, $f$ should be vanish on $M$, $i.e.$, $f(x)=0,\forall x \in M$, otherwise, fix $f(y)>0$ for $y\in K-\left\{ 0 \right\}$, we can find $\lambda \in \mathbb{R}$ $s.t.$ $\lambda f(x)=f(\lambda x)>f(y)$.

Then by theorem \@ref(thm:riesz), we have $f(x)=x'v$ for some $v$, write $v=(\alpha,\phi)$ where $\alpha\in \mathbb{R}$ and $\phi \in \mathbb{R}^{n}$. Since $f(x)>0$ for nonzero $x \in K$, $\alpha$ and $\phi$ should strictly positive, then
$$
- \alpha \bm{S_0'\theta}+\bm{\phi'D'\theta}=0
$$
which implies $-\alpha \bm{S_0}+\bm{D\phi}=\bm{0}$ and thus $\frac{\phi}{\alpha}$ is a state price vector as required.

$\impliedby$, Suppose $(-\bm{S_0'\theta},\bm{D'\theta}) \in K$, then, $\bm{\psi'D'\theta}\le 0$ and $\bm{D'\theta}\ge 0$, note $\psi \gg 0$ force $\bm{D'\theta}=\bm{0}$, thus $K \cap M=\left\{ \bm{0} \right\}$ as required.


::::


::: {.exercise  name=""}

1

:::


::: {.solution}

Given above.

:::


::: {.exercise  name=""}

2

:::


::: {.solution}

Setup:
$$
\bm{S_0}=(1,S_0)', \bm{D}=\begin{bmatrix}
                              1+r	& 1+r	\\
                              uS_0	& dS_0	\\
                          \end{bmatrix}
$$
then the state price should be
$$
\bm{\psi}=\bm{D^{-1}S_0}=[(-u+1+r)S_0,(d-1-r)S_0]'\gg 0
$$
then claim follows.

:::


::: {.exercise  name=""}

3

:::


::: {.solution}

No. Let $\psi=(\frac{1}{3},\frac{1}{3})$, it's a state price vector.

:::


::: {.exercise  name=""}

4

:::


::: {.solution}

Note column space of $D$ is just $\left\{ \lambda\cdot(1,2,3)': \lambda \in \mathbb{R} \right\}$, which excluded $\overline{q}$, therefore there is no state price vector and thus arbitrage exists.

:::
