---
title: Homework 2
author:
  - Xie zejian
bibliography: references.bib
date: "Last compiled on `r format(Sys.time(), '%H:%M, %d %B, %Y')`"
output:
  bookdown::pdf_document2:
    toc: false
    includes:
      in_header: preamble.tex
    latex_engine: xelatex
---

# Optimality and Asset Pricing {-}

Suppose the market $(\bm{D,S_0})$ is given, an agent is defined by an utility function $U:\mathbb{R}^{n}\to \mathbb{R}$ and an endowment $\bm{\varepsilon}\in \mathbb{R}^{n}_{+}$. Our optimal target is
$$
\max _{\theta \in A} U(\bm{\varepsilon+D'\theta}) 
$$
where
$$
A=\left\{ \bm{S_0'\theta}\le 0, \bm{\varepsilon+D'\theta \ge  0} \right\}
$$
and we assume there is $\bm{\theta _0} \text{ s.t. } \bm{D'\theta_0}>0$, that along with absence of arbitrage implies the optimal $\theta^*$ satisfy $\bm{S_0'\theta}=0$, otherwise we can invest some on $\bm{\theta_0}$ and get a better portfolio.

Note $A=\left\{  \bm{S_0'\theta}= 0, \bm{\varepsilon+D'\theta \ge  0}  \right\}$ is closed and bounded if there is no arbitrage and assume $U$ is continuous, we have 


::: {.proposition  name=""}

The optimal problem has solution iff there is no arbitrage.

:::


::: {.theorem #utility-state name=""}

If in optimal solution $\bm{\theta^{*}}$,  $\bm{c^{*}}=\bm{\varepsilon+D'\theta^{*}}\gg 0$, $\nabla U\gg 0$ at $\bm{c}^{*}$, 
There exist $\lambda>0 \text{ s.t. }$ $\lambda \nabla U(\bm{c}^{*})$ is a state price vector.

:::

:::: {.proof}

Suppose $\bm{\theta^{*}}$ is solution, for any portfolio $\bm{\theta}  \text{ s.t. } \bm{S_0'\theta}=0$, if we combine $\bm{\theta^{*}}$ and $\bm{\theta}$, utility will be
$$
g(\alpha)=U[\varepsilon+\bm{D'}(\bm{\theta^{*}}+\alpha \bm{\theta})]=U(\bm{c^{*}}+\alpha \bm{D'\theta})
$$
where $\bm{c}^{*}=\bm{\varepsilon+D'\theta^{*}}$. As $\bm{\theta^{*}}$ is the solution, we have FOC on $\alpha=0$:
$$
g'(0)=\left[ \nabla U(\bm{c}^{*}) \right]'\bm{D'\theta}=[\bm{D}\nabla U(\bm{c}^{*})]'\bm{\theta}=0
$$
that implies $\bm{D}\nabla  U(\bm{c^{*}})=\mu \bm{S}_{0}$ for some $\mu \in \mathbb{R}$. It's remaining to show that $\mu>0$. Take $\bm{\theta_0}$ in assumption, we have
$$
\mu \bm{S_0'\theta_0}=\left[ \nabla U(\bm{c}^{*}) \right]'\bm{D'\theta_0}>0
$$
thus $\mu>0$ as required.

::::
 
Since convex function automatically satisfy SOC, we have

::: {.corollary #concave-iff name=""}

If $U$ is concave and strictly increasing, $\bm{c^{*}}\gg 0$, then $\bm{\theta^{*}}$ is the optimal solution iff $\lambda \nabla U(\bm{c^{*}})$ is a state price vector for some $\lambda >0$.

:::


::: {.exercise  name=""}

Given market
$$
\bm{D}=\begin{bmatrix}
           10	& 	0\\
           0    &10     \\
       \end{bmatrix}, 
       \bm{S_0}=\begin{bmatrix}
                                   4    \\
                                   2    \\
                               \end{bmatrix}
$$
and agent
$$
U(\bm{x})=\log x_1+\log x_2, 
\bm{\varepsilon}=\begin{bmatrix}
    1   \\
    100 \\
\end{bmatrix} 
$$

:::


::: {.solution}

All the state price vector is given by:
$$
\bm{\psi}\in \left\{ \bm{D^{-1}S_0}=\frac{1}{10}\bm{S_0} \right\}
$$
by \@ref(cor:concave-iff) we have
$$
\lambda \nabla U(\bm{c^{*}})=
\lambda \begin{bmatrix}
     \frac{1}{c_1}	\\
     \frac{1}{c_2}	\\
 \end{bmatrix}=
\lambda \begin{bmatrix}
     \frac{1}{1+10\theta_1}	\\
     \frac{1}{100+10\theta_2}	\\
 \end{bmatrix}=\frac{1}{10} \bm{S_0}
$$
also $4\theta_1+2\theta_2=0$, we have
$$
\bm{\theta}=\begin{bmatrix}
                \frac{49}{20}	\\
                -\frac{49}{10}	\\
            \end{bmatrix}, \lambda=10.2
$$
the risk-neutral probability is $\bm{p}=[\frac{2}{3},\frac{1}{3}]'$ and thus the price of $X$ is
$$
\psi_0\bm{p'X}=\frac{3}{5}\cdot{15}=9
$$

:::


::: {.exercise  name=""}

Given market
$$
\bm{D}=\begin{bmatrix}
 20&          0	& 	2\\
    0&       10    &1     \\
       \end{bmatrix}, 
       \bm{S_0}=\begin{bmatrix}
                                   4    \\
                                   2    \\
                               \end{bmatrix}
$$
and agent
$$
U(\bm{x})=x_1^{\alpha}+x_2^{\alpha}+x_3^{\alpha}, 
\bm{\varepsilon}=\begin{bmatrix}
    10   \\
    50 
    \\  
    100 \\
\end{bmatrix} 
$$

:::


::: {.solution}

All the state price vector is given by
$$
\bm{\psi}\in \left\{ 
\begin{bmatrix}
    0	\\
    0	\\
    2	\\
\end{bmatrix}+
x\begin{bmatrix}
    1	\\
    1	\\
    -10	\\
\end{bmatrix}
:x\in (0,\frac{1}{5})
\right\}
$$
and
$$
\bm{c^{*}}=\begin{bmatrix}
               10+20\theta_1	\\
               50+10\theta_2	\\
               100+2\theta_1+\theta_2	\\
           \end{bmatrix}, \lambda \nabla U(\bm{c^{*}})=\lambda \alpha
           \begin{bmatrix}
               c_1^{\alpha-1}	\\
               c_2^{\alpha-1}	\\
               c_3^{\alpha-1}	\\
           \end{bmatrix}
$$
Note the first two coordinate keep the same, thus $\bm{\theta}=(1,-2)'$. Therefore
$$
\left( \frac{10}{3} \right)^{\alpha-1}=\frac{2-10x}{x}\implies x=\frac{2\cdot 3^{\alpha-1}}{10^{\alpha-1}+10\cdot 3^{\alpha-1}}
$$
and hence:
$$
\begin{aligned}
    \bm{\psi}&=\left( x,x,2-10x \right)'
    \\
    \lambda&=\frac{x}{\alpha 30^{\alpha-1}}=
\frac{\frac{2}{\alpha}\cdot 10^{1-\alpha}}{10^{\alpha-1}+10\cdot 3^{\alpha-1}}
\end{aligned}
$$
The risk-neutral probability and the price is given by
$$
\bm{p}=\frac{1}{2\cdot 3^{\alpha-1}+10^{\alpha-1}}\left[ 3^{\alpha-1},3^{\alpha-1},10^{\alpha-1} \right]',
$$

$$
\psi_0\bm{X'p}=\frac{25\cdot 3^{\alpha-1}+10\cdot10^{\alpha-1}}{2\cdot 3^{\alpha-1}+10^{\alpha-1}}\cdot(2-8x)=\frac{50\cdot 3^{\alpha-1}+20\cdot 10^{\alpha-1}}{10^{\alpha-1}+10\cdot 3^{\alpha-1}}        
$$








:::
