
# Single Period Model

## Simple Example

Suppose one buy a call option $C$ which payoff $V_1=(S_1-K)^{+}$ at time $1$, $S_1$
can be $uS_0>K$ or $dS_0<K$ determined in probability space $(\left\{ H,T \right\},2^{\left\{ H,T \right\}},\mathop{{}\mathbb{P}})$.
To replicate such option, we construct our portfolio by buying
$\Delta_0$ stock and investing remaining in risk-free asset at return $r$:
$$
(V_0-\Delta_0S_0)(1+r)+\Delta_0S_1=(S_1-K)^{+}
$$
solve:
$$
V_0=\frac{p V_1(H)+qV_1(T)}{1+r},\Delta_0= \frac{V_1(H)-V_1(T)}{S_1(H)-S_1(T)}
$$
where $p=\frac{1+r-d}{u-d},q=1-p$.

$p$ and $q$ can be then seen as probability assigned to $\mathop{{}\mathbb{P}}\left\{ H \right\}$ and $\mathop{{}\mathbb{P}}\left\{ T \right\}$. Then $V_0$ is just the discounted of expected value of such option, such measure $\mathop{{}\mathbb{P}}$ is called **risk-neutral**.


## State price

Suppose $\bm{S_0}\in \mathbb{R}^{N}$ is price of $N$ stocks at time $0$, 
and $\bm{D}\in \mathbb{R}^{N\times n}$ is their price at time $t$ for $n$ states. 
For any portfolio $\bm{\theta}\in \mathbb{R}^{N}$, it cost $\bm{S_0'\theta}$ and 
its value is $\bm{D'\theta}\in \mathbb{R}^{n}$ for all $n$ states. 

An arbitrage is then defined as a portfolio $\theta, s.t.$ $\bm{S'\theta}$ have different sign with $\bm{D'\theta}$.


::: {.definition  name="State price"}

A state price vector is $\bm{\psi} \in \mathbb{R}_{++}^{n}$ $s.t.$ $\bm{S_0}=\bm{D\psi}$.

:::

To justify the name of state price, suppose we want to "bet" the state of market, $i.e.$, we would like earning $\bm{1}_{state=i}$, then our portfolio supposed to be $\bm{D'\theta}=\bm{e_i}$, and it cost
$$
\bm{S_0'\theta}=\bm{\psi'D'\theta=\psi'e_i=}\psi_i
$$
so the coordinate of $\bm{\psi}$ is the price of "betting" a state.



::: {.theorem  name=""}

There is no arbitrage iff there is a state price vector.

:::


::: {.theorem #SPH name="Separating Hyperplane Theorem"}

Suppose $M$ and $K$ are closed convex cones in $\mathbb{R}^{d}$ that $M \cap K=\left\{ \bm{0} \right\}$, if $K$ isn't a liner space, then there is a nonzero linear $f$ separated them, $i.e.$, $f(x)<f(y)$ for any $x\in M$ and $y \in K- \left\{ \bm{0} \right\}$.

:::


::: {.theorem #riesz name="Riesz Representation Theorem"}

Any continuous linear function $f$ on Hilbert space $\mathcal{H}$ can be written as $f(x)=\left\langle x,v \right\rangle$ for some $v \in \mathcal{H}$.

:::

:::: {.proof}

Let $M=\left\{ (-\bm{S_0'\theta},\bm{D'\theta}):\theta \in \mathbb{R}^{N} \right\}$ and $K=\mathbb{R}_{+}\times \mathbb{R}_{+}^{n}$. Then there is no arbitrage iff $K\cap M=\left\{ \bm{0} \right\}$.

$\implies$, let $f$ be the functional in theorem \@ref(thm:SPH), note $M$ is a linear space, $f$ should be vanish on $M$, $i.e.$, $f(x)=0,\forall x \in M$, otherwise, fix $f(y)>0$ for $y\in K-\left\{ 0 \right\}$, we can find $\lambda \in \mathbb{R}$ $s.t.$ $\lambda f(x)=f(\lambda x)>f(y)$.

Then by theorem \@ref(thm:riesz), we have $f(x)=x'v$ for some $v$, write $v=(\alpha,\phi)$ where $\alpha\in \mathbb{R}$ and $\phi \in \mathbb{R}^{n}$. Since $f(x)>0$ for nonzero $x \in K$, $\alpha$ and $\phi$ should strictly positive, then
$$
- \alpha \bm{S_0'\theta}+\bm{\phi'D'\theta}=0
$$
which implies $-\alpha \bm{S_0}+\bm{D\phi}=\bm{0}$ and thus $\frac{\phi}{\alpha}$ is a state price vector as required.

$\impliedby$, Suppose $(-\bm{S_0'\theta},\bm{D'\theta}) \in K$, then, $\bm{\psi'D'\theta}\le 0$ and $\bm{D'\theta}$, which contrast to $\psi \gg 0$.


::::


::: {.exercise  name=""}

1

:::


::: {.solution}

Given above.

:::


::: {.exercise  name=""}

2

:::


::: {.solution}

Setup:
$$
\bm{S_0}=(1,S_0)', \bm{D}=\begin{bmatrix}
                              1+r	& 1+r	\\
                              uS_0	& dS_0	\\
                          \end{bmatrix}
$$
then the state price should be
$$
\bm{\psi}=\bm{D^{-1}S_0}=[(-u+1+r)S_0,(d-1-r)S_0]'\gg 0
$$
then claim follows.

:::


::: {.exercise  name=""}

3

:::


::: {.solution}

No. Let $\psi=(\frac{1}{3},\frac{1}{3})$, it's a state price vector.

:::


::: {.exercise  name=""}

4

:::


::: {.solution}

Note column space of $D$ is just $\left\{ \lambda\cdot(1,2,3)': \lambda \in \mathbb{R} \right\}$, which excluded $\overline{q}$, therefore there is no state price vector and thus arbitrage exists.

:::

### Risk-neutral probability

If $\bm{p}>0$ and $\bm{e'p}=1$, we can view $\bm{p}\in \mathbb{R}^{n}$ as a probability vector represent each state, as there is only $n$ states, we can use it to represent probability measure. Then
$$
\mathop{{}\mathbb{E}}_{}S_T=\bm{Dp}
$$
take $\bm{p=\frac{\psi}{e'\psi}}$. Then
$$
\mathop{{}\mathbb{E}}_{}S_T=\bm{\frac{D\psi}{e'\psi}}=\bm{\frac{S_0}{e'\psi}}
$$
where $\bm{e'\psi}$ is the discount on riskless borrowing. To confirm this, suppose the market allow positive riskless borrowing and we replicate it by investing a portfolio $\bm{\theta}$ for which
$$
\bm{D'\theta=e}
$$
and $\bm{\theta}$ cost $\bm{S_0'\theta=\psi'D'\theta=e'\psi}$. That is $\bm{\psi_0}=\bm{e'\theta}$ is the riskless discount, $\text{ i.e. } \frac{1}{\psi_0}=e^{rT}$. 

If probability vector $\bm{p}$ also let $\mathop{{}\mathbb{E}}_{}S_{T}$ have the same value, we said it's a risk-neutral probability measure.


A claim $C\in \mathbb{R}^{n}$ and it's said to be attainable or can be hedged if there is a portfolio $\theta$ that $\bm{D'\theta}=C$.


::: {.theorem  name=""}

With absence of arbitrage, the price of an attainable claim $C\in \mathbb{R}^{n}$ is $\bm{e'\psi}\mathop{{}\mathbb{E}}_{}C$ if $\bm{S_0}=\bm{e'\psi}\mathop{{}\mathbb{E}}_{}S_T$ for some probability measure $\bm{\psi}$.

:::


:::: {.proof}

Suppose $\bm{D'\theta=C}$, then its price should be $\bm{\theta'S_0}$
$$
\mathop{{}\mathbb{E}}_{}C=\mathop{{}\mathbb{E}}_{}\bm{D'\theta}=\frac{\bm{\theta'D\psi}}{\bm{e'\psi}}=\bm{\theta' S_0}
$$

::::

A market is said to be complete if every claim $C$ is attainable.

::: {.theorem  name=""}

The market in our setting is complete iff $N\ge n$ and $\bm{D}$ have full column rank.

:::


:::: {.proof}

Completeness is precisely equivalent row space $\mathcal{C}(\bm{D'})=\mathbb{R}^{n}$ and then claim follows.

::::

In complete market, risk-neutral measure is unique.

## Optimality and Asset Pricing

Suppose the market $(\bm{D,S_0})$ is given, an agent is defined by an utility function $U:\mathbb{R}^{n}\to \mathbb{R}$ and an endowment $\bm{\varepsilon}\in \mathbb{R}^{n}_{+}$. Our optimal target is
$$
\max _{\theta \in A} U(\bm{\varepsilon+D'\theta}) 
$$
where
$$
A=\left\{ \bm{S_0'\theta}\le 0, \bm{\varepsilon+D'\theta \ge  0} \right\}
$$
and we assume there is $\bm{\theta _0} \text{ s.t. } \bm{D'\theta_0}>0$, that along with absence of arbitrage implies the optimal $\theta^*$ satisfy $\bm{S_0'\theta}=0$, otherwise we can invest some on $\bm{\theta_0}$ and get a better portfolio.

Note $A=\left\{  \bm{S_0'\theta}= 0, \bm{\varepsilon+D'\theta \ge  0}  \right\}$ is closed and bounded if there is no arbitrage and assume $U$ is continuous, we have 


::: {.proposition  name=""}

The optimal problem has solution iff there is no arbitrage.

:::


::: {.theorem #utility-state name=""}

If in optimal solution $\bm{\theta^{*}}$,  $\bm{c^{*}}=\bm{\varepsilon+D'\theta^{*}}\gg 0$, $\nabla U\gg 0$ at $\bm{c}^{*}$, 
There exist $\lambda>0 \text{ s.t. }$ $\lambda \nabla U(\bm{c}^{*})$ is a state price vector.

:::

:::: {.proof}

Suppose $\bm{\theta^{*}}$ is solution, for any portfolio $\bm{\theta}  \text{ s.t. } \bm{S_0'\theta}=0$, if we combine $\bm{\theta^{*}}$ and $\bm{\theta}$, utility will be
$$
g(\alpha)=U[\varepsilon+\bm{D'}(\bm{\theta^{*}}+\alpha \bm{\theta})]=U(\bm{c^{*}}+\alpha \bm{D'\theta})
$$
where $\bm{c}^{*}=\bm{\varepsilon+D'\theta^{*}}$. As $\bm{\theta^{*}}$ is the solution, we have FOC on $\alpha=0$:
$$
g'(0)=\left[ \nabla U(\bm{c}^{*}) \right]'\bm{D'\theta}=[\bm{D}\nabla U(\bm{c}^{*})]'\bm{\theta}=0
$$
that implies $\bm{D}\nabla  U(\bm{c^{*}})=\mu \bm{S}_{0}$ for some $\mu \in \mathbb{R}$. It's remaining to show that $\mu>0$. Take $\bm{\theta_0}$ in assumption, we have
$$
\mu \bm{S_0'\theta_0}=\left[ \nabla U(\bm{c}^{*}) \right]'\bm{D'\theta_0}>0
$$
thus $\mu>0$ as required.

::::
 
Since convex function automatically satisfy SOC, we have

::: {.corollary #concave-iff name=""}

If $U$ is concave and strictly increasing, $\bm{c^{*}}\gg 0$, then $\bm{\theta^{*}}$ is the optimal solution iff $\lambda \nabla U(\bm{c^{*}})$ is a state price vector for some $\lambda >0$.

:::

### Expected Utility Function

Now we consider a special case of utility:
$$
U(\bm{c})=\mathop{{}\mathbb{E}}_{}u(c)=\bm{p'u}
$$
where $u:\mathbb{R}_{+}\to \mathbb{R}$ is concave and increasing and $\bm{u}=[u(c_1),u(c_2  ),\dots,u(c_n )]'$. 

Then we have
$$
\nabla U(\bm{c})=
                \begin{bmatrix}
                     p_1u'(c_1)	\\
                     p_2u'(c_2)	\\
                     \vdots \\
                     p_nu'(c_n)	\\
                 \end{bmatrix}
$$
theorem \@ref(thm:utility-state) yields
$$
\bm{S_0}=\bm{D\psi}=\lambda \bm{D} \nabla U(\bm{c}^{*})= \mathop{{}\mathbb{E}}_{} \left[ \lambda S_{T}\cdot u'(c) \right] 
$$
where
$$
\bm{\psi}=\lambda
\begin{bmatrix}
p_1u'(c_1)	\\
p_2u'(c_2)	\\
\vdots \\
p_nu'(c_n)	\\
\end{bmatrix}
$$
thus we can define risk-neutral measure $\mathbb{Q}$ by $\bm{\psi}$,$\bm{S_0}=\frac{1}{\psi_0}\mathop{{}\mathbb{E}}_{}^{\mathbb{Q}}S_{T}$.


::: {.exercise  name=""}

Given market
$$
\bm{D}=\begin{bmatrix}
           10	& 	0\\
           0    &10     \\
       \end{bmatrix}, 
       \bm{S_0}=\begin{bmatrix}
                                   4    \\
                                   2    \\
                               \end{bmatrix}
$$
and agent
$$
U(\bm{x})=\log x_1+\log x_2, 
\bm{\varepsilon}=\begin{bmatrix}
    1   \\
    100 \\
\end{bmatrix} 
$$

:::


::: {.solution}

All the state price vector is given by:
$$
\bm{\psi}\in \left\{ \bm{D^{-1}S_0}=\frac{1}{10}\bm{S_0} \right\}
$$
by \@ref(cor:concave-iff) we have
$$
\lambda \nabla U(\bm{c^{*}})=
\lambda \begin{bmatrix}
     \frac{1}{c_1}	\\
     \frac{1}{c_2}	\\
 \end{bmatrix}=
\lambda \begin{bmatrix}
     \frac{1}{1+10\theta_1}	\\
     \frac{1}{100+10\theta_2}	\\
 \end{bmatrix}=\frac{1}{10} \bm{S_0}
$$
also $4\theta_1+2\theta_2=0$, we have
$$
\bm{\theta}=\begin{bmatrix}
                \frac{49}{20}	\\
                -\frac{49}{10}	\\
            \end{bmatrix}, \lambda=10.2
$$
the risk-neutral probability is $\bm{p}=[\frac{2}{3},\frac{1}{3}]'$ and thus the price of $X$ is
$$
\bm{p'X}=15
$$

:::


::: {.exercise  name=""}

Given market
$$
\bm{D}=\begin{bmatrix}
 20&          0	& 	2\\
    0&       10    &1     \\
       \end{bmatrix}, 
       \bm{S_0}=\begin{bmatrix}
                                   4    \\
                                   2    \\
                               \end{bmatrix}
$$
and agent
$$
U(\bm{x})=x_1^{\alpha}+x_2^{\alpha}+x_3^{\alpha}, 
\bm{\varepsilon}=\begin{bmatrix}
    10   \\
    50 
    \\  
    100 \\
\end{bmatrix} 
$$

:::


::: {.solution}

All the state price vector is given by
$$
\bm{\psi}\in \left\{ 
\begin{bmatrix}
    0	\\
    0	\\
    2	\\
\end{bmatrix}+
x\begin{bmatrix}
    1	\\
    1	\\
    -10	\\
\end{bmatrix}
:x\in (0,\frac{1}{5})
\right\}
$$
and
$$
\bm{c^{*}}=\begin{bmatrix}
               10+20\theta_1	\\
               50+10\theta_2	\\
               100+2\theta_1+\theta_2	\\
           \end{bmatrix}, \lambda \nabla U(\bm{c^{*}})=\lambda \alpha
           \begin{bmatrix}
               c_1^{\alpha-1}	\\
               c_2^{\alpha-1}	\\
               c_3^{\alpha-1}	\\
           \end{bmatrix}
$$
Note the first two coordinate keep the same, thus $\bm{\theta}=(1,-2)'$. Therefore
$$
\left( \frac{10}{3} \right)^{\alpha-1}=\frac{2-10x}{x}\implies x=\frac{2\cdot 3^{\alpha-1}}{10^{\alpha-1}+10\cdot 3^{\alpha-1}}
$$
and hence:
$$
\lambda=\frac{x}{\alpha 30^{\alpha-1}}=
\frac{\frac{2}{\alpha}\cdot 10^{1-\alpha}}{10^{\alpha-1}+10\cdot 3^{\alpha-1}}
$$
The risk-neutral probability and the price is given by
$$
\bm{p}=\frac{1}{2\cdot 3^{\alpha-1}+10^{\alpha-1}}\left[ 3^{\alpha-1},3^{\alpha-1},10^{\alpha-1} \right]',
$$

$$
\bm{X'p}=\frac{25\cdot 3^{\alpha-1}+10\cdot10^{\alpha-1}}{2\cdot 3^{\alpha-1}+10^{\alpha-1}}
$$








:::






## Discrete Martingale

Under risk-neutral measure, for each time $k$, we have
$$
\psi_{0}\mathop{{}\mathbb{E}}_{k}{S}_{k+1}=S_{k}
$$
thus if we define the discounted stock price as $\widetilde{S}_{k}=\psi_0^{k} S_{k}$(where each $\psi_0$ can be vary by time so it should be $\prod_{i=1} ^{k} \psi_{0,k}$ but we abuse notation here), then $\widetilde{S}$ became a martingale. That implies the discounted claim $\widetilde{V}$ is also a martingale.

Now let $(\varphi_n,\psi_n)$ be the amount of stock and bound at time $n$, the portfolio we holding value:
$$
V_n=\varphi_{n}S_n+\psi_{n}B_n
$$
since the portfolio is self-financing, the should equal to the value at the start of $n+1$(when the price is remain the same):
$$
V_n=\varphi_{n+1}S_n+\psi_{n+1}B_n
$$
Put them together and take discount, we have
$$
\widetilde{V}_n=\varphi_{n+1}\widetilde{S}_{n}+\psi_{n+1}=\varphi_{n}\widetilde{S}_{n}+\psi_{n}
$$
we have
$$
\widetilde{V}_{n+1}-\widetilde{V}_n=\varphi_{n+1}(\widetilde{S}_{n+1}-\widetilde{S}_n)
$$
By induction we have
$$
\widetilde{V}_n=V_0+\sum_{i=0}^{n-1}\varphi_{i+1}(\widetilde{S}_{i+1}-\widetilde{S}_{i})
$$
that is a martingale by invoking following lemma:


::: {.lemma  name=""}

Suppose process $X=\left\{ X_{t} \right\}_{t\in \mathbb{N}}$ is adapted to $\mathbb{F}=\left\{ \mathcal{F}_t \right\}_{t \in \mathbb{N}}$ and $\left\{ \varphi_i \right\}_{i \in \mathbb{N^{+}}}$ is $\mathbb{F}$-predictable. Then
$$
\left\{ Z_n\triangleq Z_0+\sum_{i=0}^{n-1}\varphi_{i+1}(X_{i+1}-X_i) \right\}_{n \in \mathbb{N}}
$$
is a martingale if so is $X$.

:::

Now we turn to stocks market consist $N$ stocks, construct sample space as $\Omega$ be all possible path $(\mathbb{R}^{N})^{T}$. The absence of arbitrage give a risk-neutral measure for which
$$
S_{t-1}=\psi_{0}\mathop{{}\mathbb{E}}_{S_{t-1}}S_{t}
$$
and as before, take discount $\widetilde{S}_{t}=\psi_{0}^{t}S_{t}$ we have a martingale. And we claim that absence of martingale is equivalent to existence of risk-neutral measure.


